# Site-wide settings
# ------------------
title: turtle's blog

author:
  name: turtle
  email: turtle@turtlebyturtle.ca

# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
description: >
  on occasion, my hyperfixations manifest into something one might consider "useful," at which point they end up on this blog.

# Build settings
# --------------
remote_theme: jekyll/minima@d4d779a

# Minima requires the following plugins:
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  quiet_deps: true
  silence_deprecations: [import]


# Minima-specific settings
# -----------------------------------------------------------------
minima:
  skin: solarized

  nav_pages:
    - about.md

  show_excerpts: true

  date_format: "%b %d, %Y"

  social_links:
    - title: bluesky
      icon: fa-brands fa-bluesky
      url: "https://bsky.app/profile/turtlebyturtle.com"
    - title: rss
      icon: fa-solid fa-rss
      url: "https://turtlebyturtle.github.io/feed.xml"
      
  hide_site_feed_link: true
