# Site-wide settings
# ------------------
title: turtlebyturtle blog

author:
  name: turtlebyturtle
  email: placeholder@nothing.com

# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
description: >
  Welcome to my site of assorted nonsense!


# Build settings
# --------------
remote_theme: jekyll/minima@d4d779a

# Minima requires the following plugins:
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Uncomment the following setting if you wish to disable deprecation warnings
#   from newer versions of sass converter. Adapt as required.
# sass:
#   quiet_deps: true
#   silence_deprecations: [import]


# Minima-specific settings
# -----------------------------------------------------------------
minima:
  skin: auto

  nav_pages:
    - about.md

  show_excerpts: true

#   e.g. Nov 14, 2023
  date_format: "%b-%d-%Y"

  social_links:
    - title: Bluesky
      icon: bluesky
      url: "https://bsky.app/profile/turtlebyturtle.com"

  hide_site_feed_link: false
